name: Jiyoonblog
url: https://huangdii.github.io/
baseurl: 
description:  Always keen to learn more!
github: https://www.github.com/huangdii
#twitter: http://www.twitter.com/
#facebook: http://www.facebook.com
linkedin: https://www.linkedin.com/in/jiyoon-hwang-954787130/
email: jiyoon[at]tamu.edu
#disqus: diqus-username
# Google Analytics
google_analytics: G-KDY7TYLD7N
og_image: "/images/showcase.jpg"
##Make sure to edit the above fields, especially for disqus.


highlighter: rouge
markdown: kramdown
kramdown:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"